vich_uploader:
    db_driver: orm

    mappings:
       picture:
           uri_prefix: /images/pictures
           upload_destination: '%kernel.project_dir%/public/images/pictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: true
